---
title: "Fix At-Risk"
format: html
---

```{r}
library(tidyverse)
library(glue)
library(readxl)
```

```{r}
fy <- 2025

path_data <- glue(
  "C:/Users",
  "{Sys.getenv('USERNAME')}",
  "OneDrive - District of Columbia Public Schools",
  "DCPS Budget - Data",
  "Personnel",
  "485",
  .sep = "/"
)

path_clean <- glue("{path_data}/Clean/{fy}")
```

```{r}
data_485_wide <-
  read_csv(
    glue("{path_clean}/485_{fy}_wide.csv"),
    col_types = str_c(str_dup("c", 23), str_dup("d", 105), str_dup("c", 7)),
    na = ""
  )

data_485 <-
  read_csv(
    glue("{path_clean}/485_{fy}.csv"),
    col_types = str_c(str_dup("c", 31), str_dup("d", 1), str_dup("c", 3)),
    na = ""
  ) %>%
  rename(agency = fund_agency)

data_025 <-
  read_xlsx("r025.xlsx", col_types = c(rep("text", 7), rep("numeric", 9))) %>%
  select(agency, ends_with("_id"), available, spend)

crosswalk_atrisk <-
  read_xlsx("crosswalk_atrisk.xlsx", col_types = "text")

crosswalk_atrisk_overage <-
  read_xlsx("crosswalk_atrisk_overage.xlsx", col_types = "text") %>%
  select(!amount_expense)
```

```{r}
available <-
  data_025 %>%
  rename(account_id_budget = account_id) %>%
  mutate(
    spend_expected = (spend / 9) * 3,
    available_yearend = available - spend_expected
  ) %>%
  filter(available_yearend > 0.00)

available_1010001 <-
  available %>%
  filter(fund_id == "1010001")

available_1010212 <-
  available %>%
  filter(fund_id == "1010212") %>%
  mutate(fund_id = "1010001")

available_400476 <-
  available %>%
  filter(program_id == "400476")
```

```{r}
needs_fix <-
  data_485 %>%
  mutate(account_id_budget = case_when(
    account_pref_4 == "7011" ~ "7011001",
    account_pref_4 == "7014" ~ "7014008",
    .default = account_id
  )) %>%
  replace_na(list(project_id = "0", award_id = "0", task_id = "0"))
```

1010212

```{r}
needs_fix_1010212 <-
  needs_fix %>%
  # use amount not accounted for in previous step as starting point
  mutate(amount_original = amount) %>%
  filter(amount_original > 0.00) %>%
  # add columns needed for join on relevant budget table
  left_join(crosswalk_atrisk, by = join_by(program_id == program_id_ge)) %>%
  filter(!is.na(program_id_ar)) %>%
  # join on relevant budget table
  left_join(available_1010212, by = join_by(
    agency,
    fund_id,
    program_id_ar == program_id,
    costcenter_id,
    project_id, award_id,
    account_id_budget
  )) %>%
  filter(available_yearend > 0.00) %>%
  # repeat this logic for each funding source
  group_by(
    agency,
    fund_id,
    program_id_ar,
    costcenter_id,
    account_id_budget,
    project_id, award_id
  ) %>%
  mutate(amount_accountgroup = sum(amount_original)) %>%
  ungroup() %>%
  mutate(multiplier = case_when(
    amount_accountgroup <= available_yearend ~ 1.00,
    .default = available_yearend / amount_accountgroup
  )) %>%
  mutate(amount_journal = amount_original * multiplier) %>%
  mutate(leftover = amount_original - amount_journal)

leftover_1010212 <-
  needs_fix_1010212 %>%
  select(
    row_485,
    fund_id, program_id, costcenter_id,
    project_id, award_id,
    account_id,
    leftover
  )

leftover_1010212
```

1010001

```{r}
needs_fix_1010001 <-
  needs_fix %>%
  left_join(leftover_1010212) %>%
  # use amount not accounted for in previous step as starting point
  mutate(amount_original = if_else(!is.na(leftover), leftover, amount)) %>%
  select(!leftover) %>%
  filter(amount_original > 0.00) %>%
  # add columns needed for join on relevant budget table
  left_join(crosswalk_atrisk, by = join_by(program_id == program_id_ge)) %>%
  filter(!is.na(program_id_ar)) %>%
  # join on relevant budget table
  left_join(available_1010001, by = join_by(
    agency,
    fund_id,
    program_id_ar == program_id,
    costcenter_id,
    project_id, award_id,
    account_id_budget
  )) %>%
  filter(available_yearend > 0.00) %>%
  # logic repeated for each funding source
  group_by(
    agency,
    fund_id,
    program_id_ar,
    costcenter_id,
    account_id_budget,
    project_id, award_id
  ) %>%
  mutate(amount_accountgroup = sum(amount_original)) %>%
  ungroup() %>%
  mutate(multiplier = case_when(
    amount_accountgroup <= available_yearend ~ 1.00,
    .default = available_yearend / amount_accountgroup
  )) %>%
  mutate(amount_journal = amount_original * multiplier) %>%
  mutate(leftover = amount_original - amount_journal)

leftover_1010001 <-
  needs_fix_1010001 %>%
  select(
    row_485,
    fund_id, program_id, costcenter_id,
    project_id, award_id,
    account_id,
    leftover
  )

leftover_1010001
```

400476

```{r}
needs_fix_400476 <-
  needs_fix %>%
  left_join(leftover_1010001) %>%
  # use amount not accounted for in previous step as starting point
  mutate(amount_original = if_else(!is.na(leftover), leftover, amount)) %>%
  select(!leftover) %>%
  filter(amount_original > 0.00) %>%
  # add columns needed for join on relevant budget table
  left_join(crosswalk_atrisk_overage, by = join_by(
    fund_id,
    costcenter_id,
    program_id == program_id_ge
  )) %>%
  filter(!is.na(program_id_ar)) %>%
  # join on relevant budget table
  left_join(available_400476, by = join_by(
    agency,
    fund_id,
    program_id_ar == program_id,
    costcenter_id,
    project_id, award_id,
    account_id_budget
  )) %>%
  filter(available_yearend > 0.00) %>%
  # logic repeated for each funding source
  group_by(
    agency,
    fund_id,
    program_id_ar,
    costcenter_id,
    account_id_budget,
    project_id, award_id
  ) %>%
  mutate(amount_accountgroup = sum(amount_original)) %>%
  ungroup() %>%
  mutate(multiplier = case_when(
    amount_accountgroup <= available_yearend ~ 1.00,
    .default = available_yearend / amount_accountgroup
  )) %>%
  mutate(amount_journal = amount_original * multiplier) %>%
  mutate(leftover = amount_original - amount_journal)
```

***

Build 485

```{r}
needs_fix_combined <-
  bind_rows(needs_fix_1010212, needs_fix_1010001, needs_fix_400476) %>%
  group_by(row_485, account_raw) %>%
  summarize(amount_journal = sum(amount_journal), .groups = "drop") %>%
  mutate(across(account_raw, \(x) str_replace(x, "amt_x", "AMT-X"))) %>%
  pivot_wider(
    names_from = account_raw, values_from = amount_journal, names_sort = TRUE
  )

accounts_present <- names(needs_fix_combined)[2:ncol(needs_fix_combined)]
```

```{r}
supporting_485 <-
  data_485_wide %>%
  select(!any_of(accounts_present)) %>%
  mutate(across(starts_with("AMT"), \(x) 0.00)) %>%
  right_join(needs_fix_combined, by = join_by(row_485)) %>%
  select(
    `REPORT AGENCY`:`HR-X7196007`,
    sort(names(.)[str_detect(names(.), "^HR-")]),
    sort(names(.)[str_detect(names(.), "^AMT")]),
    `Fund-Descr`:row_485
  ) %>%
  mutate(across(starts_with("AMT"), \(x) replace_na(x, 0.00))) %>%
  mutate(AMTTOT = rowSums(across(starts_with("AMT-")))) %>%
  arrange(row_485)

supporting_485 %>% write_csv("supporting_485.csv", na = "")
```

Journal entries

1010212

```{r}
journal_rollup_1010212 <-
  needs_fix_1010212 %>%
  group_by(
    agency,
    fund_id,
    program_id, program_id_ar,
    costcenter_id,
    account_id,
    project_id, award_id, task_id,
    account_id_budget
  ) %>%
  summarize(
    amount_journal = sum(amount_journal),
    amount_original = sum(amount_original),
    .groups = "drop"
  )
```

```{r}
from <-
  journal_rollup_1010212 %>%
  select(
    agency,
    fund_id,
    program_id,
    costcenter_id,
    account_id,
    project_id, award_id, task_id,
    amount_journal
  ) %>%
  mutate(subtask_id = "0", .before = amount_journal) %>%
  rename_with(\(x) str_c("from_", x))

to <-
  journal_rollup_1010212 %>%
  mutate(fund_id = "1010212") %>%
  select(
    agency,
    fund_id,
    program_id = program_id_ar,
    costcenter_id,
    account_id,
    project_id, award_id, task_id,
    amount_journal
  ) %>%
  mutate(subtask_id = "0", .before = amount_journal) %>%
  rename_with(\(x) str_c("to_", x))
```

```{r}
journal_1010212 <-
  from %>%
  bind_cols(to) %>%
  bind_cols(
    select(journal_rollup_1010212, amount_original, account_id_budget)
  ) %>%
  mutate(blank_1 = NA_character_, .before = "to_agency") %>%
  mutate(blank_2 = NA_character_, .before = "amount_original") %>%
  left_join(mutate(available_1010212, fund_id = "1010212"), by = join_by(
    to_agency == agency,
    to_fund_id == fund_id,
    to_program_id == program_id,
    to_costcenter_id == costcenter_id,
    to_project_id == project_id, to_award_id == award_id,
    account_id_budget
  )) %>%
  mutate(left_after = amount_original - to_amount_journal) %>%
  mutate(step = "1010212", .after = blank_2)
```

1010001

```{r}
journal_rollup_1010001 <-
  needs_fix_1010001 %>%
  group_by(
    agency,
    fund_id,
    program_id, program_id_ar,
    costcenter_id,
    account_id,
    project_id, award_id, task_id,
    account_id_budget
  ) %>%
  summarize(
    amount_journal = sum(amount_journal),
    amount_original = sum(amount_original),
    .groups = "drop"
  )
```

```{r}
from <-
  journal_rollup_1010001 %>%
  select(
    agency,
    fund_id,
    program_id,
    costcenter_id,
    account_id,
    project_id, award_id, task_id,
    amount_journal
  ) %>%
  mutate(subtask_id = "0", .before = amount_journal) %>%
  rename_with(\(x) str_c("from_", x))

to <-
  journal_rollup_1010001 %>%
  select(
    agency,
    fund_id,
    program_id = program_id_ar,
    costcenter_id,
    account_id,
    project_id, award_id, task_id,
    amount_journal
  ) %>%
  mutate(subtask_id = "0", .before = amount_journal) %>%
  rename_with(\(x) str_c("to_", x))
```

```{r}
journal_1010001 <-
  from %>%
  bind_cols(to) %>%
  bind_cols(
    select(journal_rollup_1010001, amount_original, account_id_budget)
  ) %>%
  mutate(blank_1 = NA_character_, .before = "to_agency") %>%
  mutate(blank_2 = NA_character_, .before = "amount_original") %>%
  left_join(available_1010001, by = join_by(
    to_agency == agency,
    to_fund_id == fund_id,
    to_program_id == program_id,
    to_costcenter_id == costcenter_id,
    to_project_id == project_id, to_award_id == award_id,
    account_id_budget
  )) %>%
  mutate(left_after = amount_original - to_amount_journal) %>%
  mutate(step = "1010001", .after = blank_2)
```

400476

```{r}
journal_rollup_400476 <-
  needs_fix_400476 %>%
  group_by(
    agency,
    fund_id,
    program_id, program_id_ar,
    costcenter_id,
    account_id,
    project_id, award_id, task_id,
    account_id_budget
  ) %>%
  summarize(
    amount_journal = sum(amount_journal),
    amount_original = sum(amount_original),
    .groups = "drop"
  )
```

```{r}
from <-
  journal_rollup_400476 %>%
  select(
    agency,
    fund_id,
    program_id,
    costcenter_id,
    account_id,
    project_id, award_id, task_id,
    amount_journal
  ) %>%
  mutate(subtask_id = "0", .before = amount_journal) %>%
  rename_with(\(x) str_c("from_", x))

to <-
  journal_rollup_400476 %>%
  mutate(program_id = "400476") %>%
  select(
    agency,
    fund_id,
    program_id,
    costcenter_id,
    account_id,
    project_id, award_id, task_id,
    amount_journal
  ) %>%
  mutate(subtask_id = "0", .before = amount_journal) %>%
  rename_with(\(x) str_c("to_", x))
```

```{r}
journal_400476 <-
  from %>%
  bind_cols(to) %>%
  bind_cols(
    select(journal_rollup_400476, amount_original, account_id_budget)
  ) %>%
  mutate(blank_1 = NA_character_, .before = "to_agency") %>%
  mutate(blank_2 = NA_character_, .before = "amount_original") %>%
  left_join(available_400476, by = join_by(
    to_agency == agency,
    to_fund_id == fund_id,
    to_program_id == program_id,
    to_costcenter_id == costcenter_id,
    to_project_id == project_id, to_award_id == award_id,
    account_id_budget
  )) %>%
  mutate(left_after = amount_original - to_amount_journal) %>%
  mutate(step = "400476", .after = blank_2)
```

Combined

```{r}
journal <-
  bind_rows(
    journal_1010212,
    journal_1010001,
    journal_400476
  )

journal %>% write_csv("journal.csv", na = "")
```

```{r}
Sys.time()
```
