---
title: "Fix Cost Centers"
format: html
---

```{r}
library(tidyverse)
library(glue)
library(readxl)
```

```{r}
fy <- 2025

path_data <- glue(
  "C:/Users",
  "{Sys.getenv('USERNAME')}",
  "OneDrive - District of Columbia Public Schools",
  "DCPS Budget - Data",
  "Personnel",
  "485",
  .sep = "/"
)

path_clean <- glue("{path_data}/Clean/{fy}")
```

```{r}
data_485_wide <-
  read_csv(
    glue("{path_clean}/485_{fy}_wide.csv"),
    col_types = str_c(str_dup("c", 23), str_dup("d", 105), str_dup("c", 7)),
    na = ""
  )

data_485 <-
  read_csv(
    glue("{path_clean}/485_{fy}.csv"),
    col_types = str_c(str_dup("c", 31), str_dup("d", 1), str_dup("c", 3)),
    na = ""
  )

data_025 <-
  read_xlsx("r025.xlsx", col_types = c(rep("text", 7), rep("numeric", 5))) %>%
  select(agency, ends_with("_id"), available)

crosswalk <-
  read_xlsx("crosswalk_dept_costcenter.xlsx", col_types = "text")
```

```{r}
needs_fix <-
  data_485 %>%
  left_join(crosswalk, by = join_by(department_id)) %>%
  filter(costcenter_id %in% crosswalk$costcenter_id_peoplesoft) %>%
  filter(fund_id == "1010001") %>%
  filter(costcenter_id != costcenter_id_peoplesoft) %>%
  replace_na(list(project_id = "0", award_id = "0"))
```

```{r}
from <-
  needs_fix %>%
  select(
    agency = fund_agency,
    fund_id,
    program_id,
    costcenter_id,
    account_id,
    project_id, award_id, task_id,
    amount
  ) %>%
  mutate(subtask_id = NA_character_, .before = amount) %>%
  rename_with(\(x) str_c("from_", x))

to <-
  needs_fix %>%
  select(
    agency = fund_agency,
    fund_id,
    program_id,
    costcenter_id = costcenter_id_peoplesoft,
    account_id,
    project_id, award_id, task_id,
    amount
  ) %>%
  mutate(subtask_id = NA_character_, .before = amount) %>%
  rename_with(\(x) str_c("to_", x))
```

```{r}
available <-
  data_025 %>%
  rename_with(\(x) str_c("to_", x))
```

```{r}
journal <-
  from %>%
  bind_cols(to) %>%
  mutate(blank_1 = NA_character_, .before = "to_agency") %>%
  mutate(blank_2 = NA_character_) %>%
  mutate(to_amount_original = to_amount) %>%
  left_join(available) %>%
  replace_na(list(to_available = 0)) %>%
  mutate(
    from_amount = case_when(
      to_available <= 0 ~ 0,
      to_available < to_amount ~ to_available,
      to_available >= to_amount ~ to_amount
    ),
    to_amount = case_when(
      to_available <= 0 ~ 0,
      to_available < to_amount ~ to_available,
      to_available >= to_amount ~ to_amount
    )
  )

journal %>% write_csv("journal.csv", na = "")
```

```{r}
supporting_485 <-
  data_485_wide %>%
  filter(row_485 %in% needs_fix$row_485) %>%
  select(!row_485)

supporting_485 %>% write_csv("supporting_485.csv", na = "")
```

```{r}
Sys.time()
```
